default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: test_app_development

  test:
    <<: *default
    database: test_app_test

  production:
    <<: *default
    database: postgresql
